/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -t
Author: Elpiedras (https://sketchfab.com/Elpiedras)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/constellation-shiba-df20a205f05a4878a24ffd72d745bde6
Title: Constellation Shiba
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";

function Controls() {
  const {
    camera,
    gl: { domElement },
  } = useThree();

  return <OrbitControls args={[camera, domElement]} />;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_13: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_21: THREE.Mesh;
  };
  materials: {
    Cuerpo: THREE.MeshStandardMaterial;
    collar: THREE.MeshStandardMaterial;
    Ojos: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.Cuerpo}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials.collar}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_21.geometry}
        material={materials.Ojos}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <Controls />
    </group>
  );
}

useGLTF.preload("/scene.gltf");
