/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -t
Author: reb_blue0712 (https://sketchfab.com/re.blue0712)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiba-komainu-shibatexturingchallenge-5f1fac63b0e34f4ba8f82f4b2774979b
Title: shiba komainu [ShibaTexturingChallenge]
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";

function Controls() {
  const {
    camera,
    gl: { domElement },
  } = useThree();

  return <OrbitControls args={[camera, domElement]} />;
}

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh;
    defaultMaterial_1: THREE.Mesh;
    defaultMaterial_2: THREE.Mesh;
  };
  materials: {
    default_001: THREE.MeshStandardMaterial;
  };
};

export function Shiba_Komainu_4(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/model/Shiba_Komainu_4/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.1}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.82}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.default_001}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.default_001}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.default_001}
          />
          <Controls />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model/Shiba_Komainu_4/scene.gltf");
