/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -t
Author: zixisun02 (https://sketchfab.com/zixisun51)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiba-faef9fe5ace445e7b2989d1c1ece361c
Title: Shiba
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";

function Controls() {
  const {
    camera,
    gl: { domElement },
  } = useThree();

  return <OrbitControls args={[camera, domElement]} />;
}

type GLTFResult = GLTF & {
  nodes: {
    Group18985_default_0: THREE.Mesh;
    Box002_default_0: THREE.Mesh;
    Object001_default_0: THREE.Mesh;
  };
  materials: {
    ["default"]: THREE.MeshBasicMaterial;
  };
};

export function Shiba_Basic_1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/ec2/model/Shiba_Basic_1/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.1} castShadow receiveShadow>
      <mesh
        geometry={nodes.Group18985_default_0.geometry}
        material={materials["default"]}
        rotation={[-Math.PI / 2, 0, 0]}
        receiveShadow
      />
      <mesh
        geometry={nodes.Box002_default_0.geometry}
        material={materials["default"]}
        rotation={[-Math.PI / 2, 0, 0]}
        receiveShadow
      />
      <mesh
        geometry={nodes.Object001_default_0.geometry}
        material={materials["default"]}
        rotation={[-Math.PI / 2, 0, 0]}
        receiveShadow
      />
      <Controls />
    </group>
  );
}

useGLTF.preload("/ec2/model/Shiba_Basic_1/scene.gltf");
