/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -t
Author: Peixe do Blender (https://sketchfab.com/PeixedoBlender)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bodyguard-shiba-7ebaaf4347034c35a7a5aa83919c2ca3
Title: Bodyguard Shiba
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";

function Controls() {
  const {
    camera,
    gl: { domElement },
  } = useThree();

  return <OrbitControls args={[camera, domElement]} />;
}

type GLTFResult = GLTF & {
  nodes: {
    Group18985_default_0_default001_0: THREE.Mesh;
  };
  materials: {
    ["default.001"]: THREE.MeshBasicMaterial;
  };
};

export function Shiba_Bodyguard_9(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/ec2/model/Shiba_Bodyguard_9/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.001}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Group18985_default_0_default001_0.geometry}
              material={materials["default.001"]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <Controls />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/ec2/model/Shiba_Bodyguard_9/scene.gltf");
