/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -t
Author: Elbolillo (https://sketchfab.com/Elbolilloduro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shibatexturingchallenge-0566573fdc5845ee99822c656e60c253
Title: ShibaTexturingChallenge
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";

function Controls() {
  const {
    camera,
    gl: { domElement },
  } = useThree();

  return <OrbitControls args={[camera, domElement]} />;
}

type GLTFResult = GLTF & {
  nodes: {
    ["Material_001-material"]: THREE.Mesh;
    ["Material-material"]: THREE.Mesh;
    ["Material_002-material"]: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
};

export function Shiba_Black_11(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/model/Shiba_Black_11/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.1}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 1.29]} rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["Material_001-material"].geometry}
              material={materials["Material.001"]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["Material-material"].geometry}
              material={materials.Material}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["Material_002-material"].geometry}
              material={materials["Material.002"]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <Controls />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model/Shiba_Black_11/scene.gltf");
