/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -t
Author: Manu.Vision (https://sketchfab.com/manu.vision)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/miniature001-50e4c685802046dc8045ed0163431bec
Title: Miniature001
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";

function Controls() {
  const {
    camera,
    gl: { domElement },
  } = useThree();

  return <OrbitControls args={[camera, domElement]} />;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_57: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_61: THREE.Mesh;
    Object_63: THREE.Mesh;
    Object_65: THREE.Mesh;
    Object_67: THREE.Mesh;
    Object_70: THREE.Mesh;
    Object_72: THREE.Mesh;
    Object_74: THREE.Mesh;
    Object_76: THREE.Mesh;
    Object_78: THREE.Mesh;
    Object_80: THREE.Mesh;
    Object_83: THREE.Mesh;
    Object_85: THREE.Mesh;
    Object_87: THREE.Mesh;
    Object_89: THREE.Mesh;
    Object_91: THREE.Mesh;
    Object_93: THREE.Mesh;
    Object_96: THREE.Mesh;
    Object_98: THREE.Mesh;
    Object_100: THREE.Mesh;
    Object_102: THREE.Mesh;
    Object_104: THREE.Mesh;
    Object_106: THREE.Mesh;
    Object_108: THREE.Mesh;
    Object_112: THREE.Mesh;
    Object_113: THREE.Mesh;
    Object_114: THREE.Mesh;
    Object_116: THREE.Mesh;
    Object_110: THREE.Mesh;
    Object_118: THREE.Mesh;
    Object_119: THREE.Mesh;
    Object_123: THREE.Mesh;
    Object_127: THREE.Mesh;
    Object_125: THREE.Mesh;
    Object_121: THREE.Mesh;
    Object_129: THREE.Mesh;
    Object_131: THREE.Mesh;
    Object_137: THREE.Mesh;
    Object_135: THREE.Mesh;
    Object_133: THREE.Mesh;
    Object_143: THREE.Mesh;
    Object_141: THREE.Mesh;
    Object_139: THREE.Mesh;
    Object_149: THREE.Mesh;
    Object_147: THREE.Mesh;
    Object_145: THREE.Mesh;
    Object_153: THREE.Mesh;
    Object_155: THREE.Mesh;
    Object_157: THREE.Mesh;
    Object_151: THREE.Mesh;
    Object_162: THREE.Mesh;
    Object_163: THREE.Mesh;
    Object_165: THREE.Mesh;
    Object_166: THREE.Mesh;
    Object_168: THREE.Mesh;
    Object_169: THREE.Mesh;
    Object_171: THREE.Mesh;
    Object_172: THREE.Mesh;
    Object_174: THREE.Mesh;
    Object_175: THREE.Mesh;
    Object_177: THREE.Mesh;
    Object_178: THREE.Mesh;
    Object_180: THREE.Mesh;
    Object_181: THREE.Mesh;
    Object_183: THREE.Mesh;
    Object_184: THREE.Mesh;
    Object_186: THREE.Mesh;
    Object_187: THREE.Mesh;
    Object_189: THREE.Mesh;
    Object_190: THREE.Mesh;
    Object_192: THREE.Mesh;
    Object_193: THREE.Mesh;
    Object_159: THREE.Mesh;
    Object_160: THREE.Mesh;
    Object_198: THREE.Mesh;
    Object_199: THREE.Mesh;
    Object_201: THREE.Mesh;
    Object_202: THREE.Mesh;
    Object_204: THREE.Mesh;
    Object_205: THREE.Mesh;
    Object_207: THREE.Mesh;
    Object_208: THREE.Mesh;
    Object_210: THREE.Mesh;
    Object_211: THREE.Mesh;
    Object_213: THREE.Mesh;
    Object_214: THREE.Mesh;
    Object_216: THREE.Mesh;
    Object_217: THREE.Mesh;
    Object_219: THREE.Mesh;
    Object_220: THREE.Mesh;
    Object_222: THREE.Mesh;
    Object_223: THREE.Mesh;
    Object_225: THREE.Mesh;
    Object_226: THREE.Mesh;
    Object_228: THREE.Mesh;
    Object_229: THREE.Mesh;
    Object_195: THREE.Mesh;
    Object_196: THREE.Mesh;
    Object_234: THREE.Mesh;
    Object_235: THREE.Mesh;
    Object_237: THREE.Mesh;
    Object_238: THREE.Mesh;
    Object_240: THREE.Mesh;
    Object_241: THREE.Mesh;
    Object_243: THREE.Mesh;
    Object_244: THREE.Mesh;
    Object_246: THREE.Mesh;
    Object_247: THREE.Mesh;
    Object_249: THREE.Mesh;
    Object_250: THREE.Mesh;
    Object_252: THREE.Mesh;
    Object_253: THREE.Mesh;
    Object_255: THREE.Mesh;
    Object_256: THREE.Mesh;
    Object_258: THREE.Mesh;
    Object_259: THREE.Mesh;
    Object_261: THREE.Mesh;
    Object_262: THREE.Mesh;
    Object_264: THREE.Mesh;
    Object_265: THREE.Mesh;
    Object_231: THREE.Mesh;
    Object_232: THREE.Mesh;
    Object_269: THREE.Mesh;
    Object_271: THREE.Mesh;
    Object_273: THREE.Mesh;
    Object_267: THREE.Mesh;
    Object_275: THREE.Mesh;
    Object_276: THREE.Mesh;
  };
  materials: {
    Wood2: THREE.MeshStandardMaterial;
    Wood5: THREE.MeshStandardMaterial;
    Wood4: THREE.MeshStandardMaterial;
    Wood3: THREE.MeshStandardMaterial;
    Wood1: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
    ["Red-ish"]: THREE.MeshStandardMaterial;
    Navy_Blue: THREE.MeshStandardMaterial;
    Table: THREE.MeshStandardMaterial;
    Window: THREE.MeshStandardMaterial;
    Leaves: THREE.MeshStandardMaterial;
    White_Shiny: THREE.MeshStandardMaterial;
    Book1_material: THREE.MeshStandardMaterial;
    Book1_side_material: THREE.MeshStandardMaterial;
    Book10_material: THREE.MeshStandardMaterial;
    Book10_side_material: THREE.MeshStandardMaterial;
    Book11_material: THREE.MeshStandardMaterial;
    Book11_side_material: THREE.MeshStandardMaterial;
    Book2_material: THREE.MeshStandardMaterial;
    Book2_side_material: THREE.MeshStandardMaterial;
    Book3_material: THREE.MeshStandardMaterial;
    Book3_side_material: THREE.MeshStandardMaterial;
    Book4_material: THREE.MeshStandardMaterial;
    Book4_side_material: THREE.MeshStandardMaterial;
    Book5_material: THREE.MeshStandardMaterial;
    Book5_side_material: THREE.MeshStandardMaterial;
    Book6_material: THREE.MeshStandardMaterial;
    Book6_side_material: THREE.MeshStandardMaterial;
    Book7_material: THREE.MeshStandardMaterial;
    Book7_side_material: THREE.MeshStandardMaterial;
    Book8_material: THREE.MeshStandardMaterial;
    Book8_side_material: THREE.MeshStandardMaterial;
    Book9_material: THREE.MeshStandardMaterial;
    Book9_side_material: THREE.MeshStandardMaterial;
    Book0_material: THREE.MeshStandardMaterial;
    ["Book0_side_material.001"]: THREE.MeshStandardMaterial;
    Book0_side_material: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
  };
};

export function Shiba_House_15(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/ec2/model/Shiba_House_15/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.05}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.48}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[4, 0, -4]}>
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.Wood2}
              position={[-0.75, 0.05, 1]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials.Wood5}
              position={[-0.75, 0, 3.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={materials.Wood4}
              position={[-0.75, 0, 6.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials.Wood5}
              position={[-0.25, 0, 7]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={materials.Wood4}
              position={[-0.25, 0, 4.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials.Wood3}
              position={[-0.25, 0, 1.5]}
              scale={[1, 1, 3]}
            />
          </group>
          <group position={[3, 0, -4]}>
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials.Wood2}
              position={[-0.75, -0.05, 1]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials.Wood3}
              position={[-0.75, 0, 3.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_22.geometry}
              material={materials.Wood4}
              position={[-0.75, 0, 6.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_24.geometry}
              material={materials.Wood3}
              position={[-0.25, -0.05, 7]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_26.geometry}
              material={materials.Wood5}
              position={[-0.25, 0, 4.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_28.geometry}
              material={materials.Wood1}
              position={[-0.25, 0, 1.5]}
              scale={[1, 1, 3]}
            />
          </group>
          <group position={[2, 0, -4]}>
            <mesh
              geometry={nodes.Object_31.geometry}
              material={materials.Wood5}
              position={[-0.75, 0.05, 1]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_33.geometry}
              material={materials.Wood3}
              position={[-0.75, 0, 3.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_35.geometry}
              material={materials.Wood4}
              position={[-0.75, 0, 6.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_37.geometry}
              material={materials.Wood5}
              position={[-0.25, -0.05, 7]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_39.geometry}
              material={materials.Wood4}
              position={[-0.25, 0, 4.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_41.geometry}
              material={materials.Wood2}
              position={[-0.25, 0, 1.5]}
              scale={[1, 1, 3]}
            />
          </group>
          <group position={[1, 0, -4]}>
            <mesh
              geometry={nodes.Object_44.geometry}
              material={materials.Wood4}
              position={[-0.75, -0.05, 1]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials.Wood5}
              position={[-0.75, 0, 3.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials.Wood3}
              position={[-0.75, 0.05, 6.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_50.geometry}
              material={materials.Wood2}
              position={[-0.25, 0, 7]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_52.geometry}
              material={materials.Wood1}
              position={[-0.25, 0, 4.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_54.geometry}
              material={materials.Wood3}
              position={[-0.25, 0, 1.5]}
              scale={[1, 1, 3]}
            />
          </group>
          <group position={[0, 0, -4]}>
            <mesh
              geometry={nodes.Object_57.geometry}
              material={materials.Wood5}
              position={[-0.75, 0, 1]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_59.geometry}
              material={materials.Wood3}
              position={[-0.75, 0.05, 3.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_61.geometry}
              material={materials.Wood1}
              position={[-0.75, 0, 6.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_63.geometry}
              material={materials.Wood2}
              position={[-0.25, -0.05, 7]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_65.geometry}
              material={materials.Wood3}
              position={[-0.25, 0, 4.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_67.geometry}
              material={materials.Wood4}
              position={[-0.25, 0, 1.5]}
              scale={[1, 1, 3]}
            />
          </group>
          <group position={[-1, 0, -4]}>
            <mesh
              geometry={nodes.Object_70.geometry}
              material={materials.Wood4}
              position={[-0.75, 0, 1]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_72.geometry}
              material={materials.Wood1}
              position={[-0.75, -0.05, 3.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_74.geometry}
              material={materials.Wood3}
              position={[-0.75, 0, 6.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_76.geometry}
              material={materials.Wood4}
              position={[-0.25, 0.05, 7]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_78.geometry}
              material={materials.Wood2}
              position={[-0.25, 0, 4.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_80.geometry}
              material={materials.Wood3}
              position={[-0.25, 0.05, 1.5]}
              scale={[1, 1, 3]}
            />
          </group>
          <group position={[-2, 0, -4]}>
            <mesh
              geometry={nodes.Object_83.geometry}
              material={materials.Wood3}
              position={[-0.75, -0.05, 1]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_85.geometry}
              material={materials.Wood2}
              position={[-0.75, 0, 3.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_87.geometry}
              material={materials.Wood5}
              position={[-0.75, -0.05, 6.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_89.geometry}
              material={materials.Wood2}
              position={[-0.25, 0, 7]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_91.geometry}
              material={materials.Wood4}
              position={[-0.25, 0, 4.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_93.geometry}
              material={materials.Wood5}
              position={[-0.25, 0.05, 1.5]}
              scale={[1, 1, 3]}
            />
          </group>
          <group position={[-3, 0, -4]}>
            <mesh
              geometry={nodes.Object_96.geometry}
              material={materials.Wood4}
              position={[-0.75, 0, 1]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_98.geometry}
              material={materials.Wood3}
              position={[-0.75, -0.05, 3.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_100.geometry}
              material={materials.Wood5}
              position={[-0.75, 0, 6.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_102.geometry}
              material={materials.Wood4}
              position={[-0.25, 0, 7]}
              scale={[1, 1, 2]}
            />
            <mesh
              geometry={nodes.Object_104.geometry}
              material={materials.Wood1}
              position={[-0.25, 0.05, 4.5]}
              scale={[1, 1, 3]}
            />
            <mesh
              geometry={nodes.Object_106.geometry}
              material={materials.Wood5}
              position={[-0.25, 0, 1.5]}
              scale={[1, 1, 3]}
            />
          </group>
          <group
            position={[0, 0.25, -1.75]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1.02, 1]}
          >
            <group scale={[1.5, 0.98, 1.5]}>
              <mesh
                geometry={nodes.Object_112.geometry}
                material={materials["Red-ish"]}
              />
              <mesh
                geometry={nodes.Object_113.geometry}
                material={materials.Navy_Blue}
              />
              <mesh
                geometry={nodes.Object_114.geometry}
                material={materials.White}
              />
            </group>
            <mesh
              geometry={nodes.Object_110.geometry}
              material={materials.Table}
            />
            <mesh
              geometry={nodes.Object_116.geometry}
              material={materials.Table}
            />
          </group>
          <group position={[0, 3.5, -3.99]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_118.geometry}
              material={materials.Wood2}
            />
            <mesh
              geometry={nodes.Object_119.geometry}
              material={materials.Window}
            />
          </group>
          <group position={[-2, 0.55, 3]} scale={[0.25, 0.38, 0.25]}>
            <group
              position={[0, 0.4, 0]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[4, 2.67, 4]}
            >
              <mesh
                geometry={nodes.Object_125.geometry}
                material={materials.Wood4}
              />
              <mesh
                geometry={nodes.Object_127.geometry}
                material={materials.Leaves}
              />
            </group>
            <mesh
              geometry={nodes.Object_121.geometry}
              material={materials.Wood2}
            />
            <mesh
              geometry={nodes.Object_123.geometry}
              material={materials.Wood1}
              position={[0, -0.4, 0]}
              scale={[1.6, 1.07, 1.6]}
            />
          </group>
          <group position={[2.85, 0.2, -1.75]} rotation={[0, 0, -Math.PI / 2]}>
            <group
              position={[0, -0.35, 0]}
              rotation={[0, 0, Math.PI / 2]}
              scale={0.5}
            >
              <mesh
                geometry={nodes.Object_135.geometry}
                material={materials.Navy_Blue}
              />
              <mesh
                geometry={nodes.Object_137.geometry}
                material={materials.Wood4}
                scale={0.2}
              />
            </group>
            <mesh
              geometry={nodes.Object_133.geometry}
              material={materials.Navy_Blue}
            />
          </group>
          <group
            position={[0.75, 0.2, 0.25]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          >
            <group
              position={[0, -0.35, 0]}
              rotation={[0, 0, Math.PI / 2]}
              scale={0.5}
            >
              <mesh
                geometry={nodes.Object_141.geometry}
                material={materials.Navy_Blue}
              />
              <mesh
                geometry={nodes.Object_143.geometry}
                material={materials.Wood4}
                scale={0.2}
              />
            </group>
            <mesh
              geometry={nodes.Object_139.geometry}
              material={materials.Navy_Blue}
            />
          </group>
          <group
            position={[-0.75, 0.2, 0.25]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          >
            <group
              position={[0, -0.35, 0]}
              rotation={[0, 0, Math.PI / 2]}
              scale={0.5}
            >
              <mesh
                geometry={nodes.Object_147.geometry}
                material={materials.Navy_Blue}
              />
              <mesh
                geometry={nodes.Object_149.geometry}
                material={materials.Wood4}
                scale={0.2}
              />
            </group>
            <mesh
              geometry={nodes.Object_145.geometry}
              material={materials.Navy_Blue}
            />
          </group>
          <group position={[-3.65, -0.7, -2]} scale={[0.25, 0.38, 0.25]}>
            <mesh
              geometry={nodes.Object_151.geometry}
              material={materials.White_Shiny}
            />
            <mesh
              geometry={nodes.Object_153.geometry}
              material={materials.Leaves}
              position={[0, 9.73, 0]}
              scale={[1.69, 0.81, 1.69]}
            />
            <mesh
              geometry={nodes.Object_155.geometry}
              material={materials.Wood1}
              position={[0, -0.4, 0]}
              scale={[1.6, 1.07, 1.6]}
            />
            <mesh
              geometry={nodes.Object_157.geometry}
              material={materials.Wood4}
              position={[0, 9.73, 0]}
              scale={[1.69, 0.81, 1.69]}
            />
          </group>
          <group
            position={[-3.75, 2.6, -0.75]}
            rotation={[0, Math.PI / 2, 0]}
            scale={1.5}
          >
            <group position={[0.03, 0, 0]}>
              <mesh
                geometry={nodes.Object_162.geometry}
                material={materials.Book1_material}
              />
              <mesh
                geometry={nodes.Object_163.geometry}
                material={materials.Book1_side_material}
              />
            </group>
            <group position={[0.23, 0, 0]}>
              <mesh
                geometry={nodes.Object_165.geometry}
                material={materials.Book10_material}
              />
              <mesh
                geometry={nodes.Object_166.geometry}
                material={materials.Book10_side_material}
              />
            </group>
            <group position={[0.24, 0, 0]}>
              <mesh
                geometry={nodes.Object_168.geometry}
                material={materials.Book11_material}
              />
              <mesh
                geometry={nodes.Object_169.geometry}
                material={materials.Book11_side_material}
              />
            </group>
            <group position={[0.05, 0, 0]}>
              <mesh
                geometry={nodes.Object_171.geometry}
                material={materials.Book2_material}
              />
              <mesh
                geometry={nodes.Object_172.geometry}
                material={materials.Book2_side_material}
              />
            </group>
            <group position={[0.06, 0, 0]}>
              <mesh
                geometry={nodes.Object_174.geometry}
                material={materials.Book3_material}
              />
              <mesh
                geometry={nodes.Object_175.geometry}
                material={materials.Book3_side_material}
              />
            </group>
            <group position={[0.11, 0, 0]}>
              <mesh
                geometry={nodes.Object_177.geometry}
                material={materials.Book4_material}
              />
              <mesh
                geometry={nodes.Object_178.geometry}
                material={materials.Book4_side_material}
              />
            </group>
            <group position={[0.13, 0, 0]}>
              <mesh
                geometry={nodes.Object_180.geometry}
                material={materials.Book5_material}
              />
              <mesh
                geometry={nodes.Object_181.geometry}
                material={materials.Book5_side_material}
              />
            </group>
            <group position={[0.14, 0, 0]}>
              <mesh
                geometry={nodes.Object_183.geometry}
                material={materials.Book6_material}
              />
              <mesh
                geometry={nodes.Object_184.geometry}
                material={materials.Book6_side_material}
              />
            </group>
            <group position={[0.16, 0, 0]}>
              <mesh
                geometry={nodes.Object_186.geometry}
                material={materials.Book7_material}
              />
              <mesh
                geometry={nodes.Object_187.geometry}
                material={materials.Book7_side_material}
              />
            </group>
            <group position={[0.19, 0, 0]}>
              <mesh
                geometry={nodes.Object_189.geometry}
                material={materials.Book8_material}
              />
              <mesh
                geometry={nodes.Object_190.geometry}
                material={materials.Book8_side_material}
              />
            </group>
            <group position={[0.22, 0, 0]}>
              <mesh
                geometry={nodes.Object_192.geometry}
                material={materials.Book9_material}
              />
              <mesh
                geometry={nodes.Object_193.geometry}
                material={materials.Book9_side_material}
              />
            </group>
            <mesh
              geometry={nodes.Object_159.geometry}
              material={materials.Book0_material}
            />
            <mesh
              geometry={nodes.Object_160.geometry}
              material={materials["Book0_side_material.001"]}
            />
          </group>
          <group
            position={[-3.75, 3.85, 0.75]}
            rotation={[0, Math.PI / 2, 0]}
            scale={1.5}
          >
            <group position={[0.03, 0, 0]}>
              <mesh
                geometry={nodes.Object_198.geometry}
                material={materials.Book1_material}
              />
              <mesh
                geometry={nodes.Object_199.geometry}
                material={materials.Book1_side_material}
              />
            </group>
            <group position={[0.23, 0, 0]}>
              <mesh
                geometry={nodes.Object_201.geometry}
                material={materials.Book10_material}
              />
              <mesh
                geometry={nodes.Object_202.geometry}
                material={materials.Book10_side_material}
              />
            </group>
            <group position={[0.24, 0, 0]}>
              <mesh
                geometry={nodes.Object_204.geometry}
                material={materials.Book11_material}
              />
              <mesh
                geometry={nodes.Object_205.geometry}
                material={materials.Book11_side_material}
              />
            </group>
            <group position={[0.05, 0, 0]}>
              <mesh
                geometry={nodes.Object_207.geometry}
                material={materials.Book2_material}
              />
              <mesh
                geometry={nodes.Object_208.geometry}
                material={materials.Book2_side_material}
              />
            </group>
            <group position={[0.06, 0, 0]}>
              <mesh
                geometry={nodes.Object_210.geometry}
                material={materials.Book3_material}
              />
              <mesh
                geometry={nodes.Object_211.geometry}
                material={materials.Book3_side_material}
              />
            </group>
            <group position={[0.11, 0, 0]}>
              <mesh
                geometry={nodes.Object_213.geometry}
                material={materials.Book4_material}
              />
              <mesh
                geometry={nodes.Object_214.geometry}
                material={materials.Book4_side_material}
              />
            </group>
            <group position={[0.13, 0, 0]}>
              <mesh
                geometry={nodes.Object_216.geometry}
                material={materials.Book5_material}
              />
              <mesh
                geometry={nodes.Object_217.geometry}
                material={materials.Book5_side_material}
              />
            </group>
            <group position={[0.14, 0, 0]}>
              <mesh
                geometry={nodes.Object_219.geometry}
                material={materials.Book6_material}
              />
              <mesh
                geometry={nodes.Object_220.geometry}
                material={materials.Book6_side_material}
              />
            </group>
            <group position={[0.16, 0, 0]}>
              <mesh
                geometry={nodes.Object_222.geometry}
                material={materials.Book7_material}
              />
              <mesh
                geometry={nodes.Object_223.geometry}
                material={materials.Book7_side_material}
              />
            </group>
            <group position={[0.19, 0, 0]}>
              <mesh
                geometry={nodes.Object_225.geometry}
                material={materials.Book8_material}
              />
              <mesh
                geometry={nodes.Object_226.geometry}
                material={materials.Book8_side_material}
              />
            </group>
            <group position={[0.22, 0, 0]}>
              <mesh
                geometry={nodes.Object_228.geometry}
                material={materials.Book9_material}
              />
              <mesh
                geometry={nodes.Object_229.geometry}
                material={materials.Book9_side_material}
              />
            </group>
            <mesh
              geometry={nodes.Object_195.geometry}
              material={materials.Book0_material}
            />
            <mesh
              geometry={nodes.Object_196.geometry}
              material={materials.Book0_side_material}
            />
          </group>
          <group
            position={[-3.75, 3.85, 0.25]}
            rotation={[0, Math.PI / 2, 0]}
            scale={1.5}
          >
            <group position={[0.03, 0, 0]}>
              <mesh
                geometry={nodes.Object_234.geometry}
                material={materials.Book1_material}
              />
              <mesh
                geometry={nodes.Object_235.geometry}
                material={materials.Book1_side_material}
              />
            </group>
            <group position={[0.23, 0, 0]}>
              <mesh
                geometry={nodes.Object_237.geometry}
                material={materials.Book10_material}
              />
              <mesh
                geometry={nodes.Object_238.geometry}
                material={materials.Book10_side_material}
              />
            </group>
            <group position={[0.24, 0, 0]}>
              <mesh
                geometry={nodes.Object_240.geometry}
                material={materials.Book11_material}
              />
              <mesh
                geometry={nodes.Object_241.geometry}
                material={materials.Book11_side_material}
              />
            </group>
            <group position={[0.05, 0, 0]}>
              <mesh
                geometry={nodes.Object_243.geometry}
                material={materials.Book2_material}
              />
              <mesh
                geometry={nodes.Object_244.geometry}
                material={materials.Book2_side_material}
              />
            </group>
            <group position={[0.06, 0, 0]}>
              <mesh
                geometry={nodes.Object_246.geometry}
                material={materials.Book3_material}
              />
              <mesh
                geometry={nodes.Object_247.geometry}
                material={materials.Book3_side_material}
              />
            </group>
            <group position={[0.11, 0, 0]}>
              <mesh
                geometry={nodes.Object_249.geometry}
                material={materials.Book4_material}
              />
              <mesh
                geometry={nodes.Object_250.geometry}
                material={materials.Book4_side_material}
              />
            </group>
            <group position={[0.13, 0, 0]}>
              <mesh
                geometry={nodes.Object_252.geometry}
                material={materials.Book5_material}
              />
              <mesh
                geometry={nodes.Object_253.geometry}
                material={materials.Book5_side_material}
              />
            </group>
            <group position={[0.14, 0, 0]}>
              <mesh
                geometry={nodes.Object_255.geometry}
                material={materials.Book6_material}
              />
              <mesh
                geometry={nodes.Object_256.geometry}
                material={materials.Book6_side_material}
              />
            </group>
            <group position={[0.16, 0, 0]}>
              <mesh
                geometry={nodes.Object_258.geometry}
                material={materials.Book7_material}
              />
              <mesh
                geometry={nodes.Object_259.geometry}
                material={materials.Book7_side_material}
              />
            </group>
            <group position={[0.19, 0, 0]}>
              <mesh
                geometry={nodes.Object_261.geometry}
                material={materials.Book8_material}
              />
              <mesh
                geometry={nodes.Object_262.geometry}
                material={materials.Book8_side_material}
              />
            </group>
            <group position={[0.22, 0, 0]}>
              <mesh
                geometry={nodes.Object_264.geometry}
                material={materials.Book9_material}
              />
              <mesh
                geometry={nodes.Object_265.geometry}
                material={materials.Book9_side_material}
              />
            </group>
            <mesh
              geometry={nodes.Object_231.geometry}
              material={materials.Book0_material}
            />
            <mesh
              geometry={nodes.Object_232.geometry}
              material={materials.Book0_side_material}
            />
          </group>
          <group
            position={[2.14, 0.32, 2.11]}
            rotation={[0, 0.84, 0]}
            scale={[0.03, 0.01, 0.03]}
          >
            <mesh
              geometry={nodes.Object_267.geometry}
              material={materials["Red-ish"]}
            />
            <mesh
              geometry={nodes.Object_269.geometry}
              material={materials["default"]}
              position={[10.17, 68.28, 6.75]}
              rotation={[-Math.PI / 2, 0, 0.87]}
              scale={[28.6, 28.6, 58.44]}
            />
            <mesh
              geometry={nodes.Object_271.geometry}
              material={materials["default"]}
              position={[10.17, 68.28, 6.75]}
              rotation={[-Math.PI / 2, 0, 0.87]}
              scale={[28.6, 28.6, 58.44]}
            />
            <mesh
              geometry={nodes.Object_273.geometry}
              material={materials["default"]}
              position={[10.17, 68.28, 6.75]}
              rotation={[-Math.PI / 2, 0, 0.87]}
              scale={[28.6, 28.6, 58.44]}
            />
          </group>
          <group
            position={[0.16, 0.44, 2.56]}
            rotation={[-2.62, -0.38, 2.57]}
            scale={0.2}
          >
            <mesh
              geometry={nodes.Object_275.geometry}
              material={materials["Red-ish"]}
            />
            <mesh
              geometry={nodes.Object_276.geometry}
              material={materials.White}
            />
          </group>
          <mesh
            geometry={nodes.Object_108.geometry}
            material={materials.White}
            position={[-4.25, 0, 0]}
          />
          <mesh
            geometry={nodes.Object_129.geometry}
            material={materials.Wood4}
            position={[-3.8, 0.7, 0]}
          />
          <mesh
            geometry={nodes.Object_131.geometry}
            material={materials.Wood4}
            position={[-3.8, -0.55, -1.5]}
          />
          <Controls />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/ec2/model/Shiba_House_15/scene.gltf");
