/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -t
Author: Panki6 (https://sketchfab.com/Panki6)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pyjama-shiba-01919bcc61b94840a4e5982536c7137b
Title: Pyjama Shiba
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";

function Controls() {
  const {
    camera,
    gl: { domElement },
  } = useThree();

  return <OrbitControls args={[camera, domElement]} />;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    ["default"]: THREE.MeshStandardMaterial;
  };
};

export function Shiba_Pyjama_6(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/model/Shiba_Pyjama_6/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.1}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["default"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <Controls />
    </group>
  );
}

useGLTF.preload("/model/Shiba_Pyjama_6/scene.gltf");
