/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -t
Author: spooneystone (https://sketchfab.com/spooneystone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paint-play-shiba-71791636dea44ece9b050d29add59bfb
Title: Paint Play Shiba
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";

function Controls() {
  const {
    camera,
    gl: { domElement },
  } = useThree();

  return <OrbitControls args={[camera, domElement]} />;
}

type GLTFResult = GLTF & {
  nodes: {
    Group18985_default_0__0: THREE.Mesh;
    Box002_default_0__0: THREE.Mesh;
    Object001_default_0__0: THREE.Mesh;
  };
  materials: {
    ["Scene_-_Root"]: THREE.MeshStandardMaterial;
  };
};

export function Shiba_Paint_10(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/model/Shiba_Paint_10/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.001}>
      <mesh
        geometry={nodes.Group18985_default_0__0.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[Math.PI, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Box002_default_0__0.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[Math.PI, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Object001_default_0__0.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[Math.PI, 0, 0]}
        scale={100}
      />
      <Controls />
    </group>
  );
}

useGLTF.preload("/model/Shiba_Paint_10/scene.gltf");
