/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -t
Author: SirMalhare (https://sketchfab.com/SirMalhare)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mr-doge-056147a63d2b499fbc973a757c49c402
Title: Mr Doge
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";

function Controls() {
  const {
    camera,
    gl: { domElement },
  } = useThree();

  return <OrbitControls args={[camera, domElement]} />;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_20: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
    material_1: THREE.MeshStandardMaterial;
    material_2: THREE.MeshStandardMaterial;
    material_3: THREE.MeshStandardMaterial;
    material_4: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.01, 0.02, 0.28]}
        rotation={[0.05, -0.02, 0]}
        scale={0}
      >
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.material}
          position={[0, 116.7, 522.93]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={370.73}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.material_1}
          position={[0, 116.7, 522.93]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={370.73}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.material_2}
          position={[0, 116.7, 522.93]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={370.73}
        />
      </group>
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.material_3}
        position={[0, -0.07, 0.56]}
        rotation={[0.77, -0.07, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.material_4}
        position={[-0.04, 0.12, 0.55]}
        rotation={[-0.09, 0, 0.45]}
        scale={0.03}
      />
      <Controls />
    </group>
  );
}

useGLTF.preload("/scene.gltf");
